//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 05:28:54 PM IST 
//
@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.discovery.co.za/ws/routes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.discovery.assignment.samarpanBhattacharya.soap;
